#!/bin/sh

set -e

echo "Running pre push hook!"
repository_path=$(git rev-parse --show-toplevel)

echo "Running isort.."
# Run isort for each python project
dirname $(git ls-files "$repository_path/*/setup.py") | xargs -I {} isort --src-path="{}" --check-only --diff "{}"

echo "Running black.."
black --check --diff "$repository_path"

echo "Running pylint.."
pylint $(git ls-files '*.py')

exit 0
